config/routes.rb
Rails.application.routes.draw do

  get 'fila/:level_id', to: 'turn#index', as: 'turn_level'
  get 'turns/:id', to: 'turn#view', as: 'view_turn'
  get 'turns/new/:level_id', to: 'turn#new', as: 'new_turn'
  post 'turns', to: 'turn#create', as: 'turns'

  resources :payments
  post 'payments/new', to: 'payments#new'
  patch 'payments/:id/sent', to: 'payments#payment_sent', as: 'payment_sent'
  post 'payments/:id/received', to: 'payments#payment_received', as: 'payment_received'
  get 'payments/:id/confirmation', to: 'payments#confirmation', as: 'payment_confirmation'

  get 'wallet', to: 'coupons#index', as: 'coupon_index'
  get 'wallet/show/:id', to: 'coupons#show', as: 'coupon_show'

  get 'aulas/:id/:login_id', to: 'rooms#show', as: 'room'

  get 'salir', to: 'logins#salir'
  get 'mi_patrocinador' => 'logins#patrocinador', as: 'patrocinador'
  get 'mis_referidos' => 'logins#index', as: 'mis_referidos'
  get 'login_activity/:id' => 'logins#login_activity', as: 'login_activity'
  get 'myturns' => 'logins#my_turns', as: 'my_turns'
  get 'turn_wizard/:level_id' => 'logins#wizard_turn', as: 'turn_wizard'
  post 'turn_wizard/:level_id/validate_referred', to: 'logins#ref_selection'

  get 'activation', to: 'logins#activation', as: 'activation'
  get 'oficina', to: 'logins#dashboard', as: 'dashboard'

  devise_for :logins
  devise_scope :login do
    get   "sign_in" => "devise/sessions#new", :as => :logins_sign_in
    get   "logins/referrals" => "devise/registrations#new", :as => :logins_referrals
  end
  devise_for :managers

  get 'terminoscond', to: 'pages#terminos', as: 'terminoscond'
  get ':url', to: 'pages#show', as: 'show_page'

  namespace :admin do
    resources :pages, :logins, :payments, :turns, :levels, :capacities, :rooms, :coupons
    get 'rooms/:id/:login_id', to: 'rooms#edit', as: 'edit_aula'
    get 'activations', to: 'payments#activations', as: 'activations'
    post 'activations/:id/activating', to: 'payments#activate', as: 'activate_login'
    post 'activations/closing_room/:id', to: 'payments#close_room', as: 'close_room'
  end

  root 'pages#index'

end

app/views/admin/pages/_form.html.erb
<%= form_for(@admin_page) do |f| %>
  <% if @admin_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_page.errors.count, "error") %> prohibited this admin_page from being saved:</h2>

      <ul>
      <% @admin_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-body">
      <div class="row">
        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label 'Titulo', class: 'control-label' %>
            <%= f.text_field :title, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label 'URL', class: 'control-label' %><br>
            <%= f.text_field :url, class: 'form-control' %>
          </div>
        </div>
        </div>
      <div class="row">
        <div class="col-md-12">
          <div class="field form-group">
            <%= f.label 'Contenido', class: 'control-label' %><br>
            <%#= f.text_area :content, rows: 15, class: 'form-control' %>
            <%#= f.cktext_area :content %>
            <%= f.text_area :content, :class => 'ckeditor' %>
          </div>
        </div>
      </div>
    </div>

  <div class="actions">
    <%= f.submit class: 'btn green' %>
  </div>
<% end %>
<script>
    $('.ckeditor').ckeditor({
        // optional config
    });
</script>

app/views/admin/pages/edit.html.erb
<h1>Editar</h1>

<%= render 'form' %>

<%= link_to 'Show', show_page_path(@admin_page.url)%> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<% @title = 'Páginas' %>

<%= link_to 'Crear Pagina', new_admin_page_path, class: 'btn blue' %>
<p></p>
<div class="portlet box green">
  <div class="portlet-title">
    <div class="caption"><i class="icon-picture"></i></div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
      <a class="reload" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th>Titulo</th>
          <th>URL (Dirección)</th>
          <th>Acciones</th>
        </tr>
        </thead>

        <tbody>
    <% @admin_pages.each do |admin_page| %>
      <tr>
        <td><%= admin_page.title %></td>
        <td><%= admin_page.url %></td>
        <td><%= link_to 'Ver en Vivo', show_page_path(admin_page.url), class: 'btn red btn-xs' %>
        <%= link_to 'Editar', edit_admin_page_path(admin_page), class: 'btn blue btn-xs'  %>
        <%= link_to 'Eliminar', admin_page, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    </div>

  </div>
</div>

<br>

app/views/admin/pages/new.html.erb
<h1>Crear Página</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_page.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @admin_page.url %>
</p>

<p>
  <strong>Content:</strong>
  <%= @admin_page.content %>
</p>

<%= link_to 'Edit', edit_admin_page_path(@admin_page) %> |
<%= link_to 'Back', admin_pages_path %>