config/routes.rb
Rails.application.routes.draw do

  get 'fila/:level_id', to: 'turn#index', as: 'turn_level'
  get 'turns/:id', to: 'turn#view', as: 'view_turn'
  get 'turns/new/:level_id', to: 'turn#new', as: 'new_turn'
  post 'turns', to: 'turn#create', as: 'turns'

  resources :payments
  post 'payments/new', to: 'payments#new'
  patch 'payments/:id/sent', to: 'payments#payment_sent', as: 'payment_sent'
  post 'payments/:id/received', to: 'payments#payment_received', as: 'payment_received'
  get 'payments/:id/confirmation', to: 'payments#confirmation', as: 'payment_confirmation'

  get 'wallet', to: 'coupons#index', as: 'coupon_index'
  get 'wallet/show/:id', to: 'coupons#show', as: 'coupon_show'

  get 'aulas/:id/:login_id', to: 'rooms#show', as: 'room'

  get 'salir', to: 'logins#salir'
  get 'mi_patrocinador' => 'logins#patrocinador', as: 'patrocinador'
  get 'mis_referidos' => 'logins#index', as: 'mis_referidos'
  get 'login_activity/:id' => 'logins#login_activity', as: 'login_activity'
  get 'myturns' => 'logins#my_turns', as: 'my_turns'
  get 'turn_wizard/:level_id' => 'logins#wizard_turn', as: 'turn_wizard'
  post 'turn_wizard/:level_id/validate_referred', to: 'logins#ref_selection'

  get 'activation', to: 'logins#activation', as: 'activation'
  get 'oficina', to: 'logins#dashboard', as: 'dashboard'

  devise_for :logins
  devise_scope :login do
    get   "sign_in" => "devise/sessions#new", :as => :logins_sign_in
    get   "logins/referrals" => "devise/registrations#new", :as => :logins_referrals
  end
  devise_for :managers

  get 'terminoscond', to: 'pages#terminos', as: 'terminoscond'
  get ':url', to: 'pages#show', as: 'show_page'

  namespace :admin do
    resources :pages, :logins, :payments, :turns, :levels, :capacities, :rooms, :coupons
    get 'rooms/:id/:login_id', to: 'rooms#edit', as: 'edit_aula'
    get 'activations', to: 'payments#activations', as: 'activations'
    post 'activations/:id/activating', to: 'payments#activate', as: 'activate_login'
    post 'activations/closing_room/:id', to: 'payments#close_room', as: 'close_room'
  end

  root 'pages#index'

end

app/models/login.rb
class Login < ActiveRecord::Base
  after_create :create_login_coupon

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :room
  has_many :payments
  has_many :coupons
  belongs_to :level
  has_and_belongs_to_many :messages
  has_many :notifications
  has_many :referrals, class_name: "Login",
           foreign_key: "sponsor_id"
  belongs_to :sponsor, class_name: "Login"


  scope :level_three, -> { where(position: 1).order(:position).limit(1) }
  scope :level_two, -> { where(position: [2,3]).order :position }
  scope :level_one, -> { where(position: [4,5,6,7]).order :position }


  #Validations
  validates :first_name, :last_name, presence: true, length: {maximum: 24}
  validates :username, presence: true, uniqueness: true, length: {maximum: 18}
  validates :identification, presence: true, uniqueness: true, numericality: true, length: {maximum: 18}
  validates :country, presence: true


  private
  def set_default_role
    self.role ||= Role.find_by_name('beginner')
  end

  def create_login_coupon
    self.coupons.create type_c: 1, name: "Swissgolden", amount: 0
    self.coupons.create type_c: 2, name: "Comisión", amount: 0

  end


end

app/controllers/admin/logins_controller.rb
class Admin::LoginsController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_admin_login, only: [:show, :edit, :update, :destroy]

  # GET /admin/logins
  # GET /admin/logins.json
  def index
    @admin_logins = Login.where('id != ?', 1000)
  end

  # GET /admin/logins/1
  # GET /admin/logins/1.json
  def show
  end

  # GET /admin/logins/new
  def new
    @admin_login = Login.new
  end

  # GET /admin/logins/1/edit
  def edit
    @sponsor = @admin_login.sponsor.username
  end

  # POST /admin/logins
  # POST /admin/logins.json
  def create
    @admin_login = Login.new(admin_login_params)

    respond_to do |format|
      if @admin_login.save
        format.html { redirect_to admin_login_path(@admin_login), notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @admin_login }
      else
        format.html { render :new }
        format.json { render json: @admin_login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/logins/1
  # PATCH/PUT /admin/logins/1.json
  def update
    respond_to do |format|
      if @admin_login.update(permitir)
        format.html { redirect_to admin_login_path(@admin_login), notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_login }
      else
        format.html { render :edit }
        format.json { render json: @admin_login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/logins/1
  # DELETE /admin/logins/1.json
  def destroy
    @admin_login.destroy
    respond_to do |format|
      format.html { redirect_to admin_logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_used
    if params[:value] == "0"
      v = false
    else
      v = true
    end

    if change_login_used(params[:id], v)
      redirect_to admin_logins_url, notice: 'Usuario Fue Actualizado'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_login
      @admin_login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_login_params
      params[:admin_login]
    end

  def permitir
    params.require(:admin_login).permit(
        :email, :username,
        :first_name, :last_name, :identification,
        :phone, :mobile, :number_account, :account_type,
        :skype, :paypal,
        :country, :city, :state,
        :level_id, :sponsor_id, :room_id, :activated, :position, :mlm_started
    )
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :authenticate_login!
  before_action :set_login, only: [:wizard_turn, :ref_selection, :my_turns]
  before_action :is_your_level?, only: :wizard_turn
  before_action :is_sponsor?, only: :login_activity

  def index
    @logins = current_login.referrals
  end

  def dashboard
    #Busca la primera página que es la del DAHSBOARD
    @dash_page = Admin::Page.find 1

  end

  def salir
    sign_out :login if login_signed_in?
    sign_out :manager if manager_signed_in?
  end

  def activation
    @title = "Activa tu cuenta"
    @payment = Payment.new
    @payment.level_id = current_login.level_id
    @payment.type_p = 0
    #@payment.coupon_id = current_login.coupons.find_by(type_c: 0).id
    @payment.amount = current_login.level.amount
    @emailadmin = Login.find(1000)


  end

  def wizard_turn
    @login_level = view_context.what_level(params[:level_id].to_i, @logged)
    #Buscar TODOS ó un referidos que su capacidad de esa fila este en status = 'pagado'
    @referrals = @logged.referrals.where("level_id >= ? AND used = ?", params[:level_id].to_i, false)
  end

  def patrocinador
    @sponsor = current_login.sponsor || current_login
  end

private
  def set_login
    @logged = Login.find current_login
  end

  def is_sponsor?
    @login = Login.find params[:id]
    if current_login.id == @login.sponsor_id
      return true
    else
      redirect_to mis_referidos_path, alert: 'No tienes permisos para acceder a esta página'
    end
  end

end

app/helpers/admin/logins_helper.rb
module Admin::LoginsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
  #si el turno del level llamado, es igual al estatus
  def turn_incomplete(level, status)
    l = Login.find current_login.id
    c = l.capacities
    #Si el status de la capacidad no esta active es porque no tiene turno y por lo tanto no ha sido completado
    if level == 1
      c.first.status == status
    elsif level == 2
      c.second.status == status
    else
      c.last.status == status
    end
  end

end

app/views/logins/_step2.html.erb
<div class="form-body">
  <ul class="nav nav-pills nav-justified steps">
    <li>
      <a href="javascript:;" class="step">
        <span class="number">1</span>
        <span class="desc"><i class="icon-ok"></i> Pagar a Turno en Posición</span>
      </a>
    </li>
    <li class="active">
      <a href="#tab2" data-toggle="tab" class="step active">
        <span class="number">2</span>
        <span class="desc"><i class="icon-ok"></i> Validar Referido</span>
      </a>
    </li>
    <li>
      <a href="javascript:;" class="step">
        <span class="number">3</span>
        <span class="desc"><i class="icon-ok"></i> Solicitar Creación de Turno</span>
      </a>
    </li>
  </ul>
  <div id="bar" class="progress progress-striped" role="progressbar">
    <div class="progress-bar progress-bar-success" style="width: 60%;"></div>
  </div>
  <div class="tab-content">
        <div class="tab-pane active" id="tab2">
          <div class="row">
            <div class="col-md-4 col-md-offset-1">
              <h3>Selecciona Tu Usuario Referido</h3>
              <p>Aquí se listarán los usuarios que hayas referido y que no haya sido usado para la creación de otro Turno. Podrás seleccionar uno de estos para continuar pero deben estar ACTIVOS.</p>
            </div>
            <div class="col-md-6">

              <div class="portlet box green">
                <div class="portlet-title">
                  <div class="caption"><i class="icon-picture"></i>Tus Referidos</div>
                  <div class="tools">
                    <a class="collapse" href="javascript:;"></a>
                    <a class="reload" href="javascript:;"></a>
                  </div>
                </div>
                <div class="portlet-body">
                  <div class="table-responsive">
                    <table class="table table-condensed table-hover">
                      <% if @referrals.empty? %>
                          No tienes Usuarios Referidos sin uso. Refiere uno nuevo y haz que pague al Turno en posición ó activa uno de los actuales.
                          <%= link_to 'Referir Nuevo Ususario', new_login_registration_path %>
                      <% else %>
                      <thead>
                      <tr>
                        <th>Usuario</th>
                        <th>Estado</th>
                        <th colspan="1"></th>
                      </tr>
                      </thead>

                      <tbody>

                          <% @referrals.each do |user| %>
                          <% u = what_level(params[:level_id].to_i, user) %>
                              <tr>
                                <td><%= user.username %></td>
                                <% if u.status != 'inactive' || 'progress' %>
                                <td>Activo</td>
                                <td>
                                  <%= form_tag(controller: "logins", action: 'ref_selection') %>
                                  <%= hidden_field_tag :referred, user.id %>
                                  <%= hidden_field_tag :level_id, params[:level_id] %>
                                  <%= submit_tag 'Seleccionar', class: 'btn green' %>
                                </td>
                                <% else %>
                                    <td><%= u.status %></td>
                                <% end %>


                              </tr>
                          <% end %>
                      </tbody>
                      <% end %>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

  </div>
</div>

app/views/logins/_step3.html.erb
<div class="form-body">
  <ul class="nav nav-pills nav-justified steps">
    <li>
      <a href="javascript:;" class="step">
        <span class="number">1</span>
        <span class="desc"><i class="icon-ok"></i> Pagar a Turno en Posición</span>
      </a>
    </li>
    <li>
      <a href="javascript:;" class="step">
        <span class="number">2</span>
        <span class="desc"><i class="icon-ok"></i> Validar Referido</span>
      </a>
    </li>
    <li class="active">
      <a href="#tab3" data-toggle="tab" class="step active">
        <span class="number">3</span>
        <span class="desc"><i class="icon-ok"></i> Solicitar Creación de Turno</span>
      </a>
    </li>
  </ul>
  <div id="bar" class="progress progress-striped" role="progressbar">
    <div class="progress-bar progress-bar-success" style="width: 90%; "></div>
  </div>
  <div class="tab-content">
        <div class="tab-pane active" id="tab3">

          <div class="row">
            <div class="col-md-4 col-md-offset-1">
              <h3>Al Fin! A la fila para Cobrar</h3>
              <p><b>Haz click en siguiente enlace y solicita tu Turno:</b></p>
            </div>
            <div class="col-md-4" style="padding-top: 30px;">
              <%= link_to new_turn_path(params[:level_id]), class: 'btn btn-lg green' do  %>
                  Solicitar Turno
                  <i class="icon-plus"></i>
              <% end %>
            </div>
          </div>
        </div>

  </div>
</div>

app/views/logins/activation.html.erb
<div class="row">
  <div class="col-md-12">
    <p>Para solicitar la activación de su cuenta debe realizar el pago a INMARKS de <strong>$<%= current_login.level.amount %></strong>.</p>

    <h4><strong>Opciones de Pago</strong></h4>
    <div class="well well-lg">

    <div class="row">
      <div class="col-md-6">
        <h4>Deposito Bancario</h4>
        <strong><%= @emailadmin.account_type %></strong><br/>
        <%= "#{@emailadmin.first_name} #{@emailadmin.last_name}" %> <br/>
        <%= @emailadmin.number_account %> <br/>
        <small><i>Realizar su deposito con su nombre y apellido</i></small>
      </div>
      <div class="col-md-6">
        <h4>Paypal</h4>
        Puede realizar a través de Paypal con su Tarjeta de debito ó crédito.
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post">

          <!-- Identify your business so that you can collect the payments. -->
          <input type="hidden" name="business"
                 value="<%= @emailadmin.email %>">

          <!-- Specify a Donate button. -->
          <input type="hidden" name="cmd" value="_donations">

          <!-- Specify details about the contribution -->
          <input type="hidden" name="item_name" value="INMARK Business School - Pago de $<%= current_login.level.amount + 5 %> para activacion">
          <input type="hidden" name="item_number" value="<%= current_login.level.name %>">
          <input type="hidden" name="amount" value="<%= current_login.level.amount + 5 %>">
          <input type="hidden" name="currency_code" value="USD">
          <input type="hidden" name="return" value="http://inmarkbs.com/activation"/>

          <!-- Display the payment button. -->
          <input type="submit" name="submit" border="0" value="Pagar Vía PAYPAL" class="btn blue">
          <img alt="" border="0" width="1" height="1"
               src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" >

        </form>
      </div>
    </div>
    </div>

    <hr/>

    <h4><strong>¿Pago realizado?</strong></h4>
    <p>Cuando haya realizado el pago, suba una imagen de su comprobante de deposito y/ó digite los datos de la transacción.</p>

  </div>
</div>

<div class="row">
  <div class="col-md-6 ">


    <%= form_for(@payment) do |f| %>
        <%= f.hidden_field :level_id %>
        <%= f.hidden_field :type_p %>
        <%#= f.hidden_field :coupon_id %>
        <%= f.hidden_field :amount %>
    <div class="form-group">
    <h5>¿Cómo realizó el pago?</h5>
        <%= f.select(:gateway, [["Deposito Bancario", "Deposito Bancario"], ["Paypal","Paypal"]], {}, class: "form-control input-xlarge") %>
    </div>

    <h5>Información del Pago <i>(# de Transacción / MTCN)</i></h5>
    <%= f.text_area :comment, size: "20x5", class: 'form-control' %>
    <br>
    <%= f.submit 'Solicitar Activación', class: 'btn btn-lg green m-icon-big payment_sent' %>
    <% end %>
  </div>

</div>

app/views/logins/dashboard.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="hola">
      <%= image_tag 'bg-welcome.jpg', class: 'img-responsive' %>
      <h2><b>¡Hola <%= [current_login.first_name, current_login.last_name].join(' ') %>!</b></h2>
    </div>
  </div>

  <% if current_login.activated == false %>
    <div class="col-md-12">
      <div class="note note-warning">
      <div class="col-md-12">

        <h3><b>Aún no estas activo/a</b></h3>
      </div>
      <div class="col-md-7">
        <p>Actívate e inicia INMARK sólo con $<%= current_login.level.amount + 5  %>. Inicia haciendo click en el siguiente botón:</p>

        <%= link_to 'Solicitar Activación', activation_path, class: 'btn btn-lg green'  %>
      </div>
        <div class="clearfix"></div>
      </div>
    </div>

  <% end %>

  <div class="col-md-12">
    <%== @dash_page.content %>
  </div>

</div><!-- FIN ROW -->

app/views/logins/index.html.erb
<% @title = 'Mis Referidos' %>

<div class="portlet box green">
  <div class="portlet-title">
    <div class="caption"><i class="icon-picture"></i>Usuarios</div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
      <a class="reload" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th>Usuario</th>
          <th>Aula</th>
          <th>Nombre</th>
          <th>Email</th>
          <th>Telefono</th>
          <th>País</th>
        </tr>
        </thead>

        <tbody>
        <% @logins.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td>
                <% if user.level_id == 1 %>
                     <%= link_to user.room_id, room_path(user.room, user.id), class: "btn label label-default" unless user.room.nil? %>
                  <% else %>
                    <%= link_to user.room_id, room_path(user.room, user.id), class: "btn label label-success" unless user.room.nil? %>
                  <% end %>

              </td>
              <td><%= "#{user.first_name} #{user.last_name}" %></td>
              <td><%= link_to user.email, "mailto:#{user.email}" %></td>
              <td><%= user.phone %></td>

              <td><%= user.country %></td>

            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/logins/login_activity.html.erb
<% @title = "Actividad de #{@login.username}" %>
<h3><b>Fila $25:</b> <%= @login.capacities.first.status %></h3>
<% if @login.capacities.second %>
<h3><b>Fila $75:</b> <%= @login.capacities.second.status %></h3>
<% end %>
<% if @login.capacities.third %>
<h3><b>Fila $125:</b> <%= @login.capacities.last.status %></h3>
<% end %>
<div class="portlet box green">
  <div class="portlet-title">
    <div class="caption"><i class="icon-picture"></i>Información</div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
      <a class="reload" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th>Turno</th>
          <th>Usuario</th>
          <th>Fila</th>
          <th>Estado</th>
          <th>Pagos</th>
        </tr>
        </thead>

        <tbody>
        <% @login.turns.each do |t| %>
            <tr>
              <td><%= t.id %></td>
              <td><%= t.login.username %></td>
              <td><%= "$#{t.level.amount}" %></td>
              <td><%= t.status %></td>
              <td><%= t.payments.size %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/logins/my_turns.html.erb
<% @title = 'Mis Turnos' %>
<div class="row">
  <div class="col-md-6">
  </div>
</div>
<div class="portlet box green">
  <div class="portlet-title">
    <div class="caption"><i class="icon-picture"></i>Fila de $25</div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
      <a class="reload" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th>Turno</th>
          <th>Usuario</th>
          <th>Estado</th>
          <th>Pagos</th>
          <th>Acciones</th>
        </tr>
        </thead>

        <tbody>
        <% @turns.each do |t| %>
            <tr>
              <td><%= t.id %></td>
              <td><%= t.login.username %></td>
              <td><%= t.status %></td>
              <td><%= t.payments.size %></td>
                  <td>
                    <%= link_to 'Ver', view_turn_path(t.id) %>
                  </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
      <% if have_capacity?(1) %>
        <% if turn_incomplete(1, 'pagado') %>
            <div class="form-actions fluid">
              <div class="row">
                <div class="col-md-4 col-md-offset-2">
                  <h3>Turno incompleto</h3>
                  <p>Finaliza la creacion del Turno en la Fila $25. Lo iniciaste pero aún esta pendiente terminarlo</p>
                </div>
                <div class="col-md-6" style="padding-top: 35px;">
                  <%= link_to 'Completar Creación', turn_wizard_path(1), class: 'btn btn-lg red' %>
                </div>
              </div>
            </div>
        <% else %>
            <div class="form-actions fluid">
              <div class="row">
                <div class="col-md-4 col-md-offset-2">
                  <h3>Crea tu Turno</h3>
                  <p>Inicia la creacion del Turno en la Fila $25. No pierdas más tiempo.</p>
                </div>
                <div class="col-md-6" style="padding-top: 35px;">
                  <%= link_to 'Crear Turno', turn_wizard_path(1), class: 'btn btn-lg green' %>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

<!-- FILA 2-->
<% if @logged.level_id > 1 %>
<div class="portlet box blue">
  <div class="portlet-title">
    <div class="caption"><i class="icon-picture"></i>Fila de $75</div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
      <a class="reload" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th>Turno</th>
          <th>Usuario</th>
          <th>Estado</th>
          <th>Pagos</th>
          <th>Acciones</th>
        </tr>
        </thead>

        <tbody>
        <% @turns2.each do |t| %>
            <tr>
              <td><%= t.id %></td>
              <td><%= t.login.username %></td>
              <td><%= t.status %></td>
              <td><%= t.payments.size %></td>
              <td>
                <%= link_to 'Ver', view_turn_path(t.id) %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <% if have_capacity?(2) %>
        <% if turn_incomplete(2, 'pagado') %>
            <div class="form-actions fluid">
              <div class="row">
                <div class="col-md-4 col-md-offset-2">
                  <h3>Turno incompleto</h3>
                  <p>Finaliza la creacion del Turno en la Fila $75. Lo iniciaste pero aún esta pendiente terminarlo</p>
                </div>
                <div class="col-md-6" style="padding-top: 35px;">
                  <%= link_to 'Completar Creación', turn_wizard_path(2), class: 'btn btn-lg red' %>
                </div>
              </div>
            </div>
        <% else %>
            <div class="form-actions fluid">
              <div class="row">
                <div class="col-md-4 col-md-offset-2">
                  <h3>Crea tu Turno</h3>
                  <p>Inicia la creacion del Turno en la Fila $75. No pierdas más tiempo.</p>
                </div>
                <div class="col-md-6" style="padding-top: 35px;">
                  <%= link_to 'Crear Turno', turn_wizard_path(2), class: 'btn btn-lg green' %>
                </div>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>
<% end %>

<!-- FILA 3-->
<% if current_login.level_id > 2 %>
    <div class="portlet box purple">
      <div class="portlet-title">
        <div class="caption"><i class="icon-picture"></i>Fila de $125</div>
        <div class="tools">
          <a class="collapse" href="javascript:;"></a>
          <a class="reload" href="javascript:;"></a>
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-condensed table-hover">
            <thead>
            <tr>
              <th>Turno</th>
              <th>Usuario</th>
              <th>Estado</th>
              <th>Pagos</th>
              <th>Acciones</th>
            </tr>
            </thead>

            <tbody>
            <% @turns3.each do |t| %>
                <tr>
                  <td><%= t.id %></td>
                  <td><%= t.login.username %></td>
                  <td><%= t.status %></td>
                  <td><%= t.payments.size %></td>
                  <td>
                    <%= link_to 'Ver', view_turn_path(t.id) %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
        <% if have_capacity?(3) %>
            <% if turn_incomplete(3, 'pagado') %>
                <div class="form-actions fluid">
                  <div class="row">
                    <div class="col-md-4 col-md-offset-2">
                      <h3>Turno incompleto</h3>
                      <p>Finaliza la creacion del Turno en la Fila $125. Lo iniciaste pero aún esta pendiente terminarlo</p>
                    </div>
                    <div class="col-md-6" style="padding-top: 35px;">
                      <%= link_to 'Completar Creación', turn_wizard_path(3), class: 'btn btn-lg red' %>
                    </div>
                  </div>
                </div>
            <% else %>
                <div class="form-actions fluid">
                  <div class="row">
                    <div class="col-md-4 col-md-offset-2">
                      <h3>Crea tu Turno</h3>
                      <p>Inicia la creacion del Turno en la Fila $125. No pierdas más tiempo.</p>
                    </div>
                    <div class="col-md-6" style="padding-top: 35px;">
                      <%= link_to 'Crear Turno', turn_wizard_path(3), class: 'btn btn-lg green' %>
                    </div>
                  </div>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/logins/patrocinador.html.erb
<% @title = "Patrocinador" %>
<div class="col-md-12">
  <div class="portlet box grey">
    <div class="portlet-title">
      <div class="caption"><i class="icon-cogs"></i>Datos del Patrocinador</div>
      <div class="tools">
        <a class="collapse" href="javascript:;"></a>
      </div>
    </div>
    <div class="portlet-body">
      <div class="margin-top-10 margin-bottom-10 clearfix">
        <table class="table table-bordered table-striped">
          <tbody>
          <tr>
            <td><b>Usuario</b></td>
            <td>
              <%= @sponsor.username %>
            </td>
          </tr>
          <tr>
            <td><b>Nombre</b></td>
            <td>
              <%= "#{@sponsor.first_name} #{@sponsor.last_name}" %>
            </td>
          </tr>
          <tr>
            <td><b>Email</b></td>
            <td>
              <%= @sponsor.email %>
            </td>
          </tr>
          <tr>
            <td><b>Teléfono</b></td>
            <td>
              <%= @sponsor.phone %>
            </td>
          </tr>
          <tr>
            <td><b>Aula de Patrocinador</b></td>
            <td>
              <% if @sponsor.level_id == 1
                   color = 'label label-default'
                 else
                   color = 'label label-success'
                 end
              %>
              <%= link_to @sponsor.room_id, room_path(@sponsor.room, @sponsor.id), class: "btn #{color}" %>
            </td>
          </tr>


          </tbody></table>
      </div>

    </div>
  </div>
</div>

app/views/logins/salir.js.erb
alert('Salio!!');

app/views/logins/wizard_turn.html.erb
<% @title = 'Pasos para Crear un Turno' %>
<!-- BEGIN PAGE CONTENT-->
<div class="row">
<div class="col-md-12">
<div class="portlet box blue" id="form_wizard_1">
<div class="portlet-title">
  <div class="caption">
    <i class="icon-reorder"></i><span class="step-title">Los 3 pasos</span>
  </div>
  <div class="tools hidden-xs">
    <a href="javascript:;" class="collapse"></a>
  </div>
</div>
<div class="portlet-body form">

<div class="form-wizard">
<% if @login_level.status == 'pagado' %>
      <%= render 'step2' %>
  <% elsif @login_level.status == 'referido' %>
      <%= render 'step3' %>
      <% else %>
        <%= render 'patrocinador' %>
      <% end %>
</div>

</div>
</div>
</div>
</div>
<!-- END PAGE CONTENT-->
<%#= javascript_include_tag "bootstrap-wizard/jquery.bootstrap.wizard.min" %>
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<!-- END PAGE LEVEL SCRIPTS -->
<!-- END JAVASCRIPTS -->