config/routes.rb
Rails.application.routes.draw do

  get 'fila/:level_id', to: 'turn#index', as: 'turn_level'
  get 'turns/:id', to: 'turn#view', as: 'view_turn'
  get 'turns/new/:level_id', to: 'turn#new', as: 'new_turn'
  post 'turns', to: 'turn#create', as: 'turns'

  resources :payments
  post 'payments/new', to: 'payments#new'
  patch 'payments/:id/sent', to: 'payments#payment_sent', as: 'payment_sent'
  post 'payments/:id/received', to: 'payments#payment_received', as: 'payment_received'
  get 'payments/:id/confirmation', to: 'payments#confirmation', as: 'payment_confirmation'

  get 'wallet', to: 'coupons#index', as: 'coupon_index'
  get 'wallet/show/:id', to: 'coupons#show', as: 'coupon_show'

  get 'aulas/:id/:login_id', to: 'rooms#show', as: 'room'

  get 'salir', to: 'logins#salir'
  get 'mi_patrocinador' => 'logins#patrocinador', as: 'patrocinador'
  get 'mis_referidos' => 'logins#index', as: 'mis_referidos'
  get 'login_activity/:id' => 'logins#login_activity', as: 'login_activity'
  get 'myturns' => 'logins#my_turns', as: 'my_turns'
  get 'turn_wizard/:level_id' => 'logins#wizard_turn', as: 'turn_wizard'
  post 'turn_wizard/:level_id/validate_referred', to: 'logins#ref_selection'

  get 'activation', to: 'logins#activation', as: 'activation'
  get 'oficina', to: 'logins#dashboard', as: 'dashboard'

  devise_for :logins
  devise_scope :login do
    get   "sign_in" => "devise/sessions#new", :as => :logins_sign_in
    get   "logins/referrals" => "devise/registrations#new", :as => :logins_referrals
  end
  devise_for :managers

  get 'terminoscond', to: 'pages#terminos', as: 'terminoscond'
  get ':url', to: 'pages#show', as: 'show_page'

  namespace :admin do
    resources :pages, :logins, :payments, :turns, :levels, :capacities, :rooms, :coupons
    get 'rooms/:id/:login_id', to: 'rooms#edit', as: 'edit_aula'
    get 'activations', to: 'payments#activations', as: 'activations'
    post 'activations/:id/activating', to: 'payments#activate', as: 'activate_login'
    post 'activations/closing_room/:id', to: 'payments#close_room', as: 'close_room'
  end

  root 'pages#index'

end

app/models/turn.rb
class Turn < ActiveRecord::Base

  belongs_to :login
  belongs_to :level
  has_many :payments


end

app/controllers/admin/turns_controller.rb
class Admin::TurnsController < ApplicationController
  before_action :authenticate_manager!
  before_action :set_admin_turn, only: [:show, :edit, :update, :destroy]

  # GET /admin/turns
  # GET /admin/turns.json
  def index
    @turns = Turn.where level_id: 1
    @turns2 = Turn.where level_id: 2
    @turns3 = Turn.where level_id: 3

    @ttotal = Turn.count
  end

  # GET /admin/turns/1
  # GET /admin/turns/1.json
  def show
  end

  # GET /admin/turns/new
  def new
    @turn = Turn.new
  end

  # GET /admin/turns/1/edit
  def edit
  end

  # POST /admin/turns
  # POST /admin/turns.json
  def create
    @turn = Turn.new(admin_turn_params)

    respond_to do |format|
      if @turn.save
        #changes STATUS
        c = view_context.what_level(@turn.level_id, @turn.login)
        c.update_attribute :status, 'active'
        change_status @turn.login, 'active'
        #FIN changes STATUS

        format.html { redirect_to admin_turn_path(@turn), notice: 'Turn was successfully created.' }
        format.json { render :show, status: :created, location: @turn }
      else
        format.html { render :new }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/turns/1
  # PATCH/PUT /admin/turns/1.json
  def update
    respond_to do |format|
      if @turn.update(admin_turn_params)
        format.html { redirect_to admin_turn_path(@turn), notice: 'Turn was successfully updated.' }
        format.json { render :show, status: :ok, location: @turn }
      else
        format.html { render :edit }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/turns/1
  # DELETE /admin/turns/1.json
  def destroy
    @turn.destroy
    respond_to do |format|
      format.html { redirect_to admin_turns_url, notice: 'Turn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_turn
      @turn = Turn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_turn_params
      params.require(:turn).permit(:login_id, :level_id, :status)
    end
end

app/controllers/turn_controller.rb
class TurnController < ApplicationController
  before_action :authenticate_login!
  before_action :is_owner?, only: :view
  before_action :is_your_level?, only: :index

  def index
    @turns = Turn.where(level_id: params[:level_id], status: 'waiting').offset(5)

    #Buscar el Turn Active de ese level
    @active = Turn.where(level_id: params[:level_id], status: ['active', 'confirmation']).first
    #Buscar los waiting de ese level
    @wfive = Turn.where(level_id: params[:level_id], status: 'waiting').limit(5)

    l = Level.find params[:level_id]
    @title = "Fila de $#{l.amount}"
  end

  def view
    @turn = Turn.find params[:id]

    #if @turn.payments.where sent: true, received: false
    #  flash.now.notice = 'Aún no has confirmado algunos PAGOS. Recuerda que los demás están ESPERANDO'
    #end
  end

  #From this method call to private method after validate it
  def new
      #si el status del capacities es referido
      if status_valid?('referido')
        @new_turn = Turn.new
      else
        redirect_to 'logins/my_turn', alert: 'No estas calificado para crear Turno'
        logger.debug "Intento de Creación de Turno sin Calificar"
      end
  end

  #this action will create the Turn
  def create
    if status_valid?('referido')
    @new_turn = Turn.new(params[:turns])

    @new_turn.level_id = params[:level_id]
    @new_turn.login_id = params[:login_id]
    @new_turn.referred = params[:referred]

    if @new_turn.save
      #after create turn, change Capacity status to Active
      change_capacity_status(params[:level_id].to_i)
      #Cambiar estatus del Login
      change_status @new_turn.login, 'Active'
      #Cambiar el REferido a USADO
      change_login_used(params[:referred], true)
      #redireccion
      redirect_to my_turns_path, notice: 'El Turno ha sido creado'
    end
    end
  end

  private
  def status_valid?(status)
    c = view_context.what_level(params[:level_id].to_i, current_login)

    if c.status == status
      return true
    else
      redirect_to root_path, alert: 'No tienes permisos para acceder a esta página'
    end
  end

  def change_capacity_status(level)
    c = view_context.what_level(level, current_login)
    c.update_attribute :status, 'active'
  end

  def is_owner?
    @turn = Turn.find(params[:id])

    if current_login.id == @turn.login_id
      return true
    else
      redirect_to root_path, alert: 'No tienes permisos para acceder a esta página'
    end
  end


end

app/helpers/admin/turns_helper.rb
module Admin::TurnsHelper
end

app/helpers/turn_helper.rb
module TurnHelper

end

app/views/admin/turns/_form.html.erb
<%= form_for(@turn, as: :turn, url: admin_turn_path(@turn)) do |f| %>
  <% if @turn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turn.errors.count, "error") %> prohibited this turn from being saved:</h2>

      <ul>
      <% @turn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-body">
      <div class="row">
        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label :login_id, class: 'control-label' %>
            <%= f.text_field :login_id, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label :level_id, class: 'control-label' %><br>
            <%= f.text_field :level_id, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label :status, class: 'control-label' %><br>
            <%= f.select(:status, [['waiting', 'waiting'], ['active', 'active'], ['confirmation', 'confirmation'], ['completed', 'completed']], {}, class: "form-control") %>
          </div>
        </div>

      </div>
    </div>



  <div class="actions">
    <%= f.submit class: 'btn green' %>
  </div>
<% end %>

app/views/admin/turns/edit.html.erb
<h1>Editando Turno <%= @turn.id %></h1>

<%= render 'form' %>

<%= link_to 'Show', admin_turn_path(@turn) %> |
<%= link_to 'Back', admin_turns_path %>

app/views/admin/turns/index.html.erb
<% @title = 'ADMIN > Turnos' %>
<div class="row">
  <div class="col-md-6">
    <%= link_to 'Crear Turno', new_admin_turn_path, class: 'btn blue' %>
<p></p>
  </div>
</div>
<div class="portlet box green">
  <div class="portlet-title">
    <div class="caption"><i class="icon-picture"></i>Fila de $25</div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
      <a class="reload" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <table class="table table-condensed table-hover">
        <thead>
        <tr>
          <th>Turno</th>
          <th>Usuario</th>
          <th>Estado</th>
          <th>Pagos</th>
          <th>Acciones</th>
        </tr>
        </thead>

        <tbody>
        <% @turns.each do |t| %>
            <tr>
              <td><%= t.id %></td>
              <td><%= t.login.username %></td>
              <td><%= t.status %></td>
              <td><%= t.payments.size %></td>
              <td>
                <%= link_to 'Ver', admin_turn_path(t), class: 'btn green btn-xs' %>
                <%= link_to 'Editar', edit_admin_turn_path(t), class: 'btn green btn-xs' %>
                <%= link_to 'Eliminar', admin_turn_path(t), method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

<!-- FILA 2-->

    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption"><i class="icon-picture"></i>Fila de $75</div>
        <div class="tools">
          <a class="collapse" href="javascript:;"></a>
          <a class="reload" href="javascript:;"></a>
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-condensed table-hover">
            <thead>
            <tr>
              <th>Turno</th>
              <th>Usuario</th>
              <th>Estado</th>
              <th>Pagos</th>
              <th>Acciones</th>
            </tr>
            </thead>

            <tbody>
            <% @turns2.each do |t| %>
                <tr>
                  <td><%= t.id %></td>
                  <td><%= t.login.username %></td>
                  <td><%= t.status %></td>
                  <td><%= t.payments.size %></td>
                  <td>
                    <%= link_to 'Ver', view_turn_path(t.id) %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>


<!-- FILA 3-->
    <div class="portlet box purple">
      <div class="portlet-title">
        <div class="caption"><i class="icon-picture"></i>Fila de $125</div>
        <div class="tools">
          <a class="collapse" href="javascript:;"></a>
          <a class="reload" href="javascript:;"></a>
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-responsive">
          <table class="table table-condensed table-hover">
            <thead>
            <tr>
              <th>Turno</th>
              <th>Usuario</th>
              <th>Estado</th>
              <th>Pagos</th>
              <th>Acciones</th>
            </tr>
            </thead>

            <tbody>
            <% @turns3.each do |t| %>
                <tr>
                  <td><%= t.id %></td>
                  <td><%= t.login.username %></td>
                  <td><%= t.status %></td>
                  <td><%= t.payments.size %></td>
                  <td>
                    <%= link_to 'Ver', view_turn_path(t.id) %>
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

app/views/admin/turns/new.html.erb
<h1>Crear Turno</h1>

<%= form_for(@turn, as: :turn, url: admin_turns_path(@turn)) do |f| %>
    <% if @turn.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@turn.errors.count, "error") %> prohibited this turn from being saved:</h2>

          <ul>
            <% @turn.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-body">
      <div class="row">
        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label :login_id, class: 'control-label' %>
            <%= f.text_field :login_id, class: 'form-control' %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label :level_id, class: 'control-label' %><br>
            <%= f.text_field :level_id, class: 'form-control' %>
          </div>
        </div>

        <div class="col-md-6">
          <div class="field form-group">
            <%= f.label :status, class: 'control-label' %><br>
            <%= f.select(:status, [['waiting', 'waiting'], ['active', 'active'], ['confirmation', 'confirmation'], ['completed', 'completed']], {}, class: "form-control") %>
          </div>
        </div>

      </div>
    </div>



    <div class="actions">
      <%= f.submit class: 'btn green' %>
    </div>
<% end %>

<%= link_to 'Back', admin_turns_path %>

app/views/admin/turns/show.html.erb
<div class="portlet box blue">
  <div class="portlet-title">
    <div class="caption"><i class="icon-reorder"></i>Información del Turno</div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
      <a class="reload" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <form role="form" class="form-horizontal">
      <div class="form-body">

        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label col-md-3"><b>Usuario:</b></label>
              <div class="col-md-9">
                <p class="form-control-static"><%= @turn.login.username %></p>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label col-md-3"><b>Estado:</b></label>
              <div class="col-md-9">
                <p class="form-control-static"><%= @turn.status %></p>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>
        <!--/row-->
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label col-md-3"><b>Creado en:</b></label>
              <div class="col-md-9">
                <p class="form-control-static"><%= @turn.created_at %></p>
              </div>
            </div>
          </div>
          <!--/span-->
          <div class="col-md-6">
            <div class="form-group">
              <label class="control-label col-md-3"><b>Fila:</b></label>
              <div class="col-md-9">
                <p class="form-control-static"><%= @turn.level.name %></p>
              </div>
            </div>
          </div>
          <!--/span-->
        </div>
        <!--/row-->
      </div>

    </form>
    <!-- END FORM-->
  </div>
</div>

<div class="portlet box green">
  <div class="portlet-title">
    <div class="caption"><i class="icon-picture"></i>Pagos al Turno</div>
    <div class="tools">
      <a class="collapse" href="javascript:;"></a>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-responsive">
      <% if @turn.payments.empty? %>
          <p>No han realizado pagos aún</p>
      <% else %>
          <table class="table table-condensed table-hover">
            <thead>
            <tr>
              <th>Turno</th>
              <th>Usuario</th>
              <th>Beneficiario</th>
              <th>Estado</th>
              <th>Método</th>
              <th>Monto USD$</th>
              <th>Creado</th>
              <th width="150">Info. de Pago</th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% @turn.payments.each do |p| %>
                <tr>
                  <td><%= p.turn_id %></td>
                  <td><%= p.login.username %></td>
                  <td><%= p.beneficiary.username %></td>
                  <td>
                    <% if p.sent && p.received == true %>
                        Confirmado
                    <% elsif p.sent == true && p.received == false %>
                        Enviado
                    <% else %>
                        Pendiente
                    <% end %>
                  </td>
                  <td><%= p.gateway %></td>
                  <td><%= p.amount %></td>
                  <td><%= p.updated_at.to_formatted_s(:short) %></td>
                  <td><small><%= p.comment %></small></td>
                  <% if p.sent == true && p.received == true %>
                      <td>----</td>
                  <% elsif p.sent == true && p.received == false %>
                      <td><%= link_to 'Confirmar Pago', payment_confirmation_path(p) %></td>
                  <% else %>
                      <td></td>
                  <% end %>
                </tr>
            <% end %>
            </tbody>

          </table>
      <% end # final de la condicional si empty? %>
    </div>
  </div>
</div>





<%= link_to 'Edit', edit_admin_turn_path(@turn) %> |
<%= link_to 'Back', admin_turns_path %>