config/routes.rb
Rails.application.routes.draw do

  get 'fila/:level_id', to: 'turn#index', as: 'turn_level'
  get 'turns/:id', to: 'turn#view', as: 'view_turn'
  get 'turns/new/:level_id', to: 'turn#new', as: 'new_turn'
  post 'turns', to: 'turn#create', as: 'turns'

  resources :payments
  post 'payments/new', to: 'payments#new'
  patch 'payments/:id/sent', to: 'payments#payment_sent', as: 'payment_sent'
  post 'payments/:id/received', to: 'payments#payment_received', as: 'payment_received'
  get 'payments/:id/confirmation', to: 'payments#confirmation', as: 'payment_confirmation'

  get 'wallet', to: 'coupons#index', as: 'coupon_index'
  get 'wallet/show/:id', to: 'coupons#show', as: 'coupon_show'

  get 'aulas/:id/:login_id', to: 'rooms#show', as: 'room'

  get 'salir', to: 'logins#salir'
  get 'mi_patrocinador' => 'logins#patrocinador', as: 'patrocinador'
  get 'mis_referidos' => 'logins#index', as: 'mis_referidos'
  get 'login_activity/:id' => 'logins#login_activity', as: 'login_activity'
  get 'myturns' => 'logins#my_turns', as: 'my_turns'
  get 'turn_wizard/:level_id' => 'logins#wizard_turn', as: 'turn_wizard'
  post 'turn_wizard/:level_id/validate_referred', to: 'logins#ref_selection'

  get 'activation', to: 'logins#activation', as: 'activation'
  get 'oficina', to: 'logins#dashboard', as: 'dashboard'

  devise_for :logins
  devise_scope :login do
    get   "sign_in" => "devise/sessions#new", :as => :logins_sign_in
    get   "logins/referrals" => "devise/registrations#new", :as => :logins_referrals
  end
  devise_for :managers

  get 'terminoscond', to: 'pages#terminos', as: 'terminoscond'
  get ':url', to: 'pages#show', as: 'show_page'

  namespace :admin do
    resources :pages, :logins, :payments, :turns, :levels, :capacities, :rooms, :coupons
    get 'rooms/:id/:login_id', to: 'rooms#edit', as: 'edit_aula'
    get 'activations', to: 'payments#activations', as: 'activations'
    post 'activations/:id/activating', to: 'payments#activate', as: 'activate_login'
    post 'activations/closing_room/:id', to: 'payments#close_room', as: 'close_room'
  end

  root 'pages#index'

end

app/views/common/_dropdown.html.erb
<!-- BEGIN TOP NAVIGATION MENU -->
<ul class="nav navbar-nav pull-right">
  <li><%= link_to 'Ir a Portada', root_path %></li>
  <% if login_signed_in? %>
<!-- BEGIN USER LOGIN DROPDOWN -->
<li class="dropdown user">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
    <%= image_tag "admin/avatar.png", width: 29, height: 29 %>
    <span class="username"><%= "#{current_login.username}" if login_signed_in? %></span>
    <i class="icon-angle-down"></i>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to edit_login_registration_path do %>
          <i class="icon-user"></i> Mi Perfil
      <% end %>

    </li>
    <% if current_login.room %>
    <li>
      <%= link_to room_path(current_login.room, current_login.id) do %>
          <i class="icon-tasks"></i> Mi Aula <span class="badge badge-success"><%= current_login.room.level.description %></span>
      <% end %>
    </li>
    <% end %>
    <li>
      <%= link_to coupon_index_path do %>
          <i class="icon-money"></i> Finanzas
      <% end %>
    </li>
    <li class="divider"></li>
    <li><a href="javascript:;" id="trigger_fullscreen"><i class="icon-move"></i> Pantalla Completa</a>
    </li>
    <li>
      <%#= link_to(salir_path, remote: true) do %>
      <%= link_to(destroy_login_session_path, method: :delete) do %>
          <i class="icon-key"></i> Salir
      <% end %>
    </li>

  </ul>
</li>
<% end %>
<!-- END USER LOGIN DROPDOWN -->

<% if manager_signed_in? %>
  <li class="dropdown user admin">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
      <%= image_tag "admin/avatar.png", width: 29, height: 29 %>
      <span class="username">Admin </span>
      <i class="icon-angle-down"></i>
    </a>
    <ul class="dropdown-menu">
      <li class="divider"></li>
      <li><a href="javascript:;" id="trigger_fullscreen"><i class="icon-move"></i> Pantalla Completa</a>
      </li>
<% end %>
    </ul>
  </li>


</ul>
<!-- END TOP NAVIGATION MENU -->

app/views/common/_menu.html.erb
<li class="tooltips" style="display:none;">
  <a href="javascript:;" >
    <i class="icon-gift"></i>
    <span class="title">Pasos para Turnos</span>
    <span class="arrow "></span>
  </a>
  <ul class="sub-menu">
    <li >
      <%= link_to turn_wizard_path(1) do %>
          <i class="icon-ok-sign"></i>
          Turno de $25
      <% end %>
    </li>
    <% if current_login.level_id > 1 %>
    <li >
      <%= link_to turn_wizard_path(2) do %>
          <i class="icon-ok-sign"></i>
          Turno de $75
      <% end %>
    </li>
    <% end %>
    <% if current_login.level_id > 2 %>
    <li >
      <%= link_to turn_wizard_path(3) do %>
          <i class="icon-ok-sign"></i>
          Turno de $125
      <% end %>
    </li>
    <% end %>
  </ul>
</li>
<li class="start">
  <%= link_to dashboard_path do %>
      <i class="icon-home"></i>
      <span class="title">Inicio</span>
  <% end %>
</li>
<li>
  <%= link_to patrocinador_path do %>
    <i class="icon-user"></i>
    <span class="title">Patrocinador</span>
  <% end %>
</li>
<li>
  <a href="javascript:;">
    <i class="icon-group"></i>
    <span class="title">Referidos</span>
    <span class="arrow "></span>
  </a>
  <ul class="sub-menu">
    <li >
      <%= link_to "Mis Referidos", mis_referidos_path %>
    </li>
    <li >
      <%= link_to "Nuevo Referido", new_login_registration_path %>
    </li>
  </ul>
</li>

<li class="" style="display: none;">
  <a href="javascript:;">
    <i class="icon-cogs"></i>
    <span class="title">Soporte</span>
    <span class="arrow "></span>
  </a>
</li>
<li class="">
  <%= link_to show_page_path('como-funciona') do %>
    <i class="icon-info-sign"></i>
    <span class="title">¿Cómo funciona?</span>
  <% end %>
</li>

<li class="">
  <%= link_to show_page_path('terminos') do %>
    <i class="icon-warning-sign"></i>
    <span class="title">Términos y Condiciones</span>
  <% end %>
</li>

app/views/common/_menu_admin.html.erb
<li class="start active">
  <a href="javascript:;">
    <i class="icon-cogs"></i>
    <span class="title">Administrador</span>
    <span class="selected"></span>
    <span class="arrow open"></span>
  </a>
  <ul class="sub-menu">
    <li >
      <%= link_to 'Aulas', admin_rooms_path %>
    </li>
    <li >
      <%= link_to 'Pagos', admin_payments_path %>
    </li>
    <li >
      <%= link_to 'Activaciones', admin_activations_path %>
    </li>
    <li >
      <%= link_to "Finanzas / Cupones", admin_coupons_path %>
    </li>
    <li >
      <%= link_to "Usuarios", admin_logins_path %>
    </li>
    <li >
      <%= link_to "Niveles", admin_levels_path %>
    </li>
    <li >
      <%= link_to "Paginas", admin_pages_path %>
    </li>

  </ul>
</li>